### ISSUE TITLE
Index dump of database files

### ISSUE THREAD

**Issue by blueteamzone** [woj-ciech/LeakLooker-X#4]
Hi, I'd love if you can add a feature where we can upload files from txt, csv, sql or json and the content of the files is indexed on a single DB. This feature would help any security researcher to index dumps of leaked databases. Usually, in my experience, the most valuable content that can be indexed using these dumped files are email addresses and passwords. What do you think about it?

**Comment by woj-ciech** [comment]
It can be done, can you upload example file?

**Comment by blueteamzone** [comment]
[125K_userpass_DB.txt](https://github.com/woj-ciech/LeakLooker-X/files/4533351/125K_userpass_DB.txt)

Try this out. The above file is easy to index but there are other files with different formats like sql, csv, json, pdf, doc and xls. If you want to find more files you can find them on torrents Collection #1 [33.4 GB *.tar.gz], Anti-Public [40 GB *.tar.gz], "Collection #2 Collection #3 Collection #4 Collection #5 Zabagur #1 Zabagur #2"  [324 GB *.tar.gz], LEAK [593 GB *.txt], Breach Compilation [41.1 GB]


Collection#1
magnet:?xt=urn:btih:BA304CAB082BAD215263BD7F66902E128ECCC7A3&dn=bigDB&tr=udp%3a%2f%2fcoppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2f9.rarbg.me%3a2710%2fannounce&tr=http%3a%2f%2fmgtracker.org%3a2710%2fannounce&tr=http%3a%2f%2fbt.careland.com.cn%3a6969%2fannounce&tr=udp%3a%2f%2fopen.demonii.com%3a1337&tr=udp%3a%2f%2fexodus.desync.com%3a6969&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969&tr=udp%3a%2f%2ftracker.pomf.se&tr=udp%3a%2f%2ftracker.blackunicorn.xyz%3a6969

Collection#2-5 + AntiPublic
magnet:?xt=urn:btih:D136B1ADDE531F38311FBF43FB96FC26DF1A34CD&dn=Collection%20%232-%235%20%26%20Antipublic&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce&tr=http%3a%2f%2ft.nyaatracker.com%3a80%2fannounce&tr=http%3a%2f%2fopentracker.xyz%3a80%2fannounce

**Comment by woj-ciech** [comment]
I read again couple times your initial comment and I still don't think I exactly get it. How should it look like? Can you elaborate?

**Comment by blueteamzone** [comment]
[analyzing-large-password-dumps](https://morphuslabs.com/analyzing-large-password-dumps-with-elastic-stack-and-python-cde7eb384f7)
[public-password-dumps-in-elk](https://outflank.nl/blog/2018/01/23/public-password-dumps-in-elk/)

The above links would make it more clear. It would be nice to have a feature where a user can upload dumped database files to Django and index the content of it inside SQLite, elastic search or Postgres. Making it easier to do research and analyze the content of the dumps. We also found some open-source tools that might help you.
                   
https://github.com/p3pperp0tts/leaks_parser/blob/master/README.md
https://gist.github.com/pasknel/62221786f2545e175581914f67694066
https://github.com/outflanknl/PasswordDump2ELK

What do you think of such a feature? Would it be feasible to index all the content on Django?

**Comment by woj-ciech** [comment]
Ahh, ok so you want to display some statistics and get access to password dumps, right? If yes then idea is cool, I like it but I don't know what it has to do with LeakLooker which searches for open databases from Binaryedge. It's not about credentials and users but more about the confidentiality of data.
It's possible to index all content in Django however faster and better way to do that is keeping the data in Elastic and use Kibana.

**Comment by blueteamzone** [comment]
Ok, It would have been nice to have that feature on leaklooker-X. However, we agree with you. Elasticsearch and Kibana would be a better option.
